### ISSUE TITLE
Gerbers.zip?

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_HW#1]
Please consider providing gerbers.zip maybe even removing individual files

**Comment by corygrant** [comment]
Feel free to zip them

**Comment by rusefillc** [comment]
@corygrant actually you already have .zip

Actually https://github.com/corygrant/CANBoard_HW/pull/4 and https://github.com/corygrant/CANBoard_HW/pull/3 since you have TWO sets of uncompressed gerbers and TWO compressed gerbers placed a bit inconsistently
