### ISSUE TITLE
Orientation of some SMTs are not in proper orientation

### ISSUE THREAD

**Issue by pknetworksolutions** [corygrant/CANBoard_HW#10]
![2023-02-24 09_39_53-JLCPCB PCBA Viewer](https://user-images.githubusercontent.com/16768797/221206349-91f6335f-5810-44d6-b27d-1013bd6be757.png)

Some components seems to be not oriented properly.

**Comment by pknetworksolutions** [comment]
Of course, using the alignment tool and based on the pink dot, we can figure something

**Comment by corygrant** [comment]
I'm not sure why the parts come in that way, it must be an issue with the part origins. 
At the very bottom of the Readme I have a photo showing the correct orientation

**Comment by pknetworksolutions** [comment]
That's what i'm gonna do. Thanks man
