### ISSUE TITLE
Something EN pin

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_HW#12]
@corygrant knows

**Comment by corygrant** [comment]
One of the PCBs @rusefillc got from JLCPCB had a strange issue where the EN pin on the TPS56339DDCR (U1) buck converter had a 2mohm resistance to ground. 
The EN pin should be completely floating (see section 7.3.2 of the datasheet). 
This led to lots of power issues:
- Power not turning on
- Power fluctuating
- Lots of noise from the board
- Power only turning on when touching the EN pin with my finger

To fix this I cut and removed the pin and now the power is stable.   
I'll update the PCB to remove the pad for EN (pin 5).
