### ISSUE TITLE
By the way why F3?

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_HW#14]
why F3 not F103 or else?

**Comment by rusefillc** [comment]
Reasons I am asking:
* I am unhappy with $11.21 price
* I am unhappy with availability - note zero stock today assuming I search right

https://jlcpcb.com/partdetail/Stmicroelectronics-STM32F303K8T6/C118318

**Comment by corygrant** [comment]
I can't remember exactly why I selected the F3. 
Most likely because:
- The original design was done in fall 2020, so F3 stock wasn't an issue
- I had a handful of F303K8 leftover from another project

Lately I've been noticing some STM32s are easier to get than others and their product line is usually very pin compatible. 
I'll see if there's an alternative part that could be easily swapped with no PCB changes. 
If not, we can talk about updating to another part number. Possibly with more pins.

**Comment by rusefillc** [comment]
> some STM32s are easier to get than others and their product line is usually very pin compatible. 

let me mention "function-compatible replacements" i.e. clones
* TL,DR: at the moment I am very impressed with Geehy APM32 which JLCPCB has many

* at the pike of chip shortage we've tried GD32F1 - those needed a few lines of changes in the HAL. while it's only few lines it takes someone extremely highly qualified to locate what few lines to adjust. I've attempted to flash GD32F4 with as-is rusEFI and it did NOT fire up. overall GD32 is known to be close but not compatible
* now comes Geehy APM32. Two data points for those
- i know an automotive produce where they have simply replaced stm32f4 with apm32f4 and they claim zero firmware changes
- my own testing so far rusEFI firmware has started on apm32f4 and even USB connectivity was running! well, at the moment we've only tested flash, GPIO and USB but that's quite impressive

that's for apm32f4 open question how that translates to apm32f1 also open question why I am so fascinated by those alternatives. I guess I am addicted to the $2 price tag.

**Comment by corygrant** [comment]
It seems like we're starting to come up out of the part shortage pit of despair, so hopefully JLC/LCSC will have things in stock soon. 

Once you filter the ST catalog by LQFP32 and CAN you're left with only a couple of options, but most of them are available in the US: 
- STM32F303K6 ($7.19)
- STM32F303K8 ($6.85)
- STM32F334K6 ($6.85)
- STM32F334K8 ($6.62)

Maybe ST is giving Digikey/Mouser/etc. preference and shipping to them first? 
I think once the inventory starts hitting LCSC their prices will go down to similar levels.

**Comment by pknetworksolutions** [comment]
Just got my boards from JLCPCB, with all the components needed. Just fill up your parts library and you can use them after that for the assembly

**Comment by Luckey1996** [comment]
> > some STM32s are easier to get than others and their product line is usually very pin compatible.
> 
> let me mention "function-compatible replacements" i.e. clones
> 
> * TL,DR: at the moment I am very impressed with Geehy APM32 which JLCPCB has many
> * at the pike of chip shortage we've tried GD32F1 - those needed a few lines of changes in the HAL. while it's only few lines it takes someone extremely highly qualified to locate what few lines to adjust. I've attempted to flash GD32F4 with as-is rusEFI and it did NOT fire up. overall GD32 is known to be close but not compatible
> * now comes Geehy APM32. Two data points for those
> 
> * i know an automotive produce where they have simply replaced stm32f4 with apm32f4 and they claim zero firmware changes
> * my own testing so far rusEFI firmware has started on apm32f4 and even USB connectivity was running! well, at the moment we've only tested flash, GPIO and USB but that's quite impressive
> 
> that's for apm32f4 open question how that translates to apm32f1 also open question why I am so fascinated by those alternatives. I guess I am addicted to the $2 price tag.

I was designing my product by using APM32F003 to replace STM8 and turns out the result was good. I have the same feeling that why not using Geehy with a extremely low price and good compatibility. Do you use already APM32F1 on your design and production? I want to know whether there are anything I need to prepare before the Mass Production. Look forward to your reply.

**Comment by rusefillc** [comment]
> Do you use already APM32F1 on your design and production? 

with stm32f4 prices going down at this point I am back to 100% stm32
* lack of USB DFU is a usability pain
* what we've designed as most budget unit turned to be unreliable with apm32f4 while stm32f4 is happy no idea what's root cause
